
#######################################################################################################################
## POSTGRES CDC ####################################################################################

services:
  postgres:
    image: postgres:15
    container_name: postgres_cdc
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${CDC_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CDC_POSTGRES_PASSWORD}
      POSTGRES_DB: app_db
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cdc_net


#######################################################################################################################
## POSTGRERS ANALYTICS ####################################################################################

  postgres_analytics:
    image: postgres:15
    container_name: postgres_analytics
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${ANL_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ANL_POSTGRES_PASSWORD}
      POSTGRES_DB: analytics_db
    volumes:
      - analytics_data:/var/lib/postgresql/data
      - ./analytics/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U analytics -d analytics_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cdc_net


#######################################################################################################################
## ZOOKEEPER ####################################################################################

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - cdc_net

#######################################################################################################################
## KAFKA ####################################################################################

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    networks:
      - cdc_net

#######################################################################################################################
## SCHEMA REGISTRY ####################################################################################

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: schema_registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
    networks:
      - cdc_net

#######################################################################################################################
## KAFKA CONNECT ####################################################################################

  kafka-connect:
    image: debezium/connect:2.5
    container_name: kafka_connect
    #depends_on:
    # - postgres
    #  - kafka
      
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

    ports:
      - "8083:8083"

    environment:
      BOOTSTRAP_SERVERS: kafka:29092

      GROUP_ID: connect-cluster

      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses

      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1

      # KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      # VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      # KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      # VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

    networks:
      - cdc_net

#######################################################################################################################
## GRAFANA ####################################################################################

  grafana:
    image: grafana/grafana:latest
    container_name: grafana

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}

    volumes:
      - ../grafana/provisioning:/etc/grafana/provisioning
      - ../grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana

    depends_on:
      postgres_analytics:
        condition: service_healthy

    networks:
      - cdc_net

    restart: unless-stopped



    
#######################################################################################################################
## CDC CONSUMER ####################################################################################

  cdc_consumer:
    build:
      context: ..
      dockerfile: docker/Dockerfile.consumer

    container_name: cdc_consumer

    depends_on:
      kafka:
        condition: service_started

      postgres_analytics:
        condition: service_healthy

    restart: unless-stopped  

    networks:
      - cdc_net
    

#######################################################################################################################
## CDC GENERATOR ####################################################################################

  generator:
    build:
      context: ..
      dockerfile: docker/Dockerfile.generator

    container_name: generator

    environment:
      CDC_POSTGRES_HOST: postgres
      CDC_POSTGRES_DB: app_db
      CDC_POSTGRES_USER: postgres
      CDC_POSTGRES_PASSWORD: postgres
      CDC_POSTGRES_PORT: 5432

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - cdc_net


#######################################################################################################################
## VOLUME - NETWORK ####################################################################################
volumes:
  postgres_data:
  analytics_data:
  grafana_data:

networks:
  cdc_net:
    driver: bridge

